# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0
  working_directory: ~/

commands:
  error_Handler:
    description: "Error Handler"
    steps:
      - run:
          command: echo "Some Error Occured!"
          when: on_fail

jobs:
  Basic_job:
    <<: *defaults
    environment:
      Circle_Compare_Url: My pipeline id is << pipeline.id >> and my git branch is << pipeline.git.branch >>
    steps:
      - run:
          name: "Print pipeline id"
          command: echo  "This is pipeline id << pipeline.id >>"
      - run: echo $Circle_Compare_Url
      - run:
          name: "Print Hello"
          command: echo $Pipeline_User
      - error_Handler

  Update_Inventory:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: Create Inventory
          command: |
            echo "[all]" > inventory
            aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --filters "Name=tag:Project, Values=Udacity3" \
            --output text >> inventory
      - error_handler

workflows:
  Demo_workflow:
    jobs:
      - Basic_job
  UdaPeople:
    jobs:
      - Update_Inventory
