# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0
  working_directory: ~/

commands:
  error_handler:
    description: "Error Handler"
    steps:
      - run:
          command: echo "Some Error Occured!"
          when: on_fail

jobs:
  Basic_job:
    <<: *defaults
    environment:
      Circle_Compare_Url: My pipeline id is << pipeline.id >> and my git branch is << pipeline.git.branch >>
    steps:
      - run:
          name: "Print pipeline id"
          command: echo  "This is pipeline id << pipeline.id >>"
      - run: echo $Circle_Compare_Url
      - run:
          name: "Print Hello"
          command: echo $Pipeline_User
      - error_handler

  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME

  Update_Inventory:
    docker:
      - image: amazon/aws-cli
      - image: circleci/node:13.8.0
    steps:
      - persist_to_workspace:
          root: ~/
          paths:
            - "inventory"
      - run:
          name: Create Inventory
          command: |
            touch inventory
            echo "[all]" > inventory
      - error_handler

  #     aws ec2 describe-instances \
  # --query 'Reservations[*].Instances[*].PublicIpAddress' \
  # --filters "Name=tag:Project, Values=Udacity3" \
  # --output text >> inventory
  display_Inventory:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/inventory
      - error_handler

workflows:
  Demo_workflow:
    jobs:
      - Basic_job
  UdaPeople:
    jobs:
      - aws-cli-cred-setup:
          context: aws
      - Update_Inventory:
          requires:
            - aws-cli-cred-setup
      - display_Inventory:
          requires:
            - Update_Inventory
