global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['_prometheusserver']

  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: prometheus_AK
        secret_key: prometheus_SK
        port: 9100